"use client";

import { useState } from "react";
import type { Acesso, Equipe, Problema, Tema } from "@/lib/operacao";
import { formatarDataHora } from "@/lib/formato";
import { Painel } from "@/components/Painel";
import { EstadoVazio } from "@/components/EstadoVazio";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import type { ContextoOperacao } from "./ConsoleOperacao";
import { CAMPO, Campo, Carregamento, Caso, FaixaNps, GRADE, lista, Medida, PILHA, SelecionarConversas, useAcao, useRecurso } from "./comum";
import { IconeDeAcao } from "@/components/IconeDeAcao";

export function ProblemasOperacao({ conversas, sufixo, administrador, tema }: ContextoOperacao & { tema: Tema | null }) {
  const r = useRecurso<{ problemas: Problema[] }>("/problemas"), equipes = useRecurso<{ equipes: Equipe[] }>("/equipes"), acesso = useRecurso<Acesso>(administrador ? "/acesso" : null), acao = useAcao();
  const [titulo, setTitulo] = useState(tema?.termos.join(" · ") ?? ""), [termos, setTermos] = useState(tema?.termos.join(", ") ?? "");
  const [ids, setIds] = useState<string[]>(tema?.conversa_ids.slice(0, 50) ?? []), [prazo, setPrazo] = useState(""), [equipe, setEquipe] = useState(""), [responsavel, setResponsavel] = useState("");
  return <div className={PILHA}><Painel titulo="Investigações e ações" nivel="dominante" legenda="As investigações conservam suas evidências mesmo ao trocar o período. Antes/depois considera todos os registros acessíveis nos mesmos canais e termos, separados pela data de resolução. A diferença é descritiva e não demonstra causalidade.">
    {!r.dado ? <Carregamento erro={r.erro} recarregar={r.recarregar} /> : !r.dado.problemas.length ? <EstadoVazio titulo="Nenhuma investigação aberta" explicacao="Abra uma investigação com evidências, responsável e prazo para acompanhar ações e resultados." /> : r.dado.problemas.map((p) => <Investigacao key={p.id} problema={p} sufixo={sufixo} recarregar={r.recarregar} equipes={equipes.dado?.equipes ?? []} acesso={acesso.dado} />)}
  </Painel><Painel titulo={tema ? "Investigar tema do radar" : "Abrir investigação"}><form className={PILHA} onSubmit={(e) => { e.preventDefault(); void acao.executar("/problemas", "POST", { titulo, termos: lista(termos), conversa_ids: ids, prazo, equipe_id: equipe || null, responsavel_id: responsavel ? Number(responsavel) : null }, () => { r.recarregar(); setTitulo(""); setIds([]); }, "Investigação aberta com as evidências selecionadas."); }}><div className={GRADE}><Campo nome="Título"><Input required minLength={3} maxLength={150} value={titulo} onChange={(e) => setTitulo(e.target.value)} /></Campo><Campo nome="Prazo"><Input required type="date" value={prazo} onChange={(e) => setPrazo(e.target.value)} /></Campo><Campo nome="Termos para acompanhar · vírgulas"><Input value={termos} onChange={(e) => setTermos(e.target.value)} /></Campo><Campo nome="Equipe"><select className={CAMPO} value={equipe} onChange={(e) => setEquipe(e.target.value)}><option value="">Sem equipe</option>{equipes.dado?.equipes.map((t) => <option key={t.id} value={t.id}>{t.nome}</option>)}</select></Campo>{administrador ? <Campo nome="Responsável"><select className={CAMPO} value={responsavel} onChange={(e) => setResponsavel(e.target.value)}><option value="">Sem responsável</option>{acesso.dado?.usuarios.filter((u) => u.ativo).map((u) => <option key={u.id} value={u.id}>{u.nome}</option>)}</select></Campo> : null}</div><SelecionarConversas conversas={conversas} selecionadas={ids} mudar={setIds} /><Button type="submit" disabled={acao.ocupado || !ids.length || ids.length > 50}><IconeDeAcao acao="abrir" />Abrir investigação</Button>{acao.feedback}</form></Painel></div>;
}

function Investigacao({ problema: p, sufixo, recarregar, equipes, acesso }: { problema: Problema; sufixo: string; recarregar: () => void; equipes: Equipe[]; acesso: Acesso | null }) {
  const acao = useAcao();
  const [estado, setEstado] = useState(p.estado), [texto, setTexto] = useState("");
  return <article className="border-b border-linha py-5"><div className="flex flex-wrap items-baseline justify-between gap-3"><h3 className="font-medium">{p.titulo}</h3><span className="rotulo-instrumento">{p.estado.replaceAll("_", " ")}</span></div><p className="mt-2 text-xs text-muted-foreground">Prazo: {p.prazo} · {equipes.find((t) => t.id === p.equipe_id)?.nome ?? "Sem equipe"} · {acesso?.usuarios.find((u) => u.id === p.responsavel_id)?.nome ?? (p.responsavel_id ? "Responsável atribuído" : "Sem responsável")}</p>
    <details className="mt-4"><summary className="cursor-pointer text-sm">Evidências e acompanhamento</summary><div className={`${PILHA} mt-4`}>{p.conversa_ids.map((id) => <Caso key={id} id={id} sufixo={sufixo} />)}<div className={GRADE}><FaixaNps titulo="NPS antes" intervalo={p.medicao.antes} /><FaixaNps titulo="NPS depois" intervalo={p.medicao.depois} /><Medida nome="Δ NPS estimado" valor={p.medicao.delta_nps} casas={1} estimativa /></div><p className="text-xs text-muted-foreground">{p.medicao.criterio}</p>{p.acoes.map((a, i) => <div key={i} className="border-l-2 border-linha pl-3"><p className="text-xs text-muted-foreground">{formatarDataHora(a.em)} · {a.estado.replaceAll("_", " ")}</p><p className="mt-1 whitespace-pre-wrap break-words text-sm text-dito-texto">{a.acao}</p></div>)}</div></details>
    <form className={`${PILHA} mt-4`} onSubmit={(e) => { e.preventDefault(); void acao.executar(`/problemas/${p.id}`, "PATCH", { estado, acao: texto }, () => { setTexto(""); recarregar(); }, "Ação registrada no histórico."); }}><div className="grid gap-3 sm:grid-cols-[12rem_1fr]"><Campo nome="Próximo estado"><select className={CAMPO} value={estado} onChange={(e) => setEstado(e.target.value)}><option value="aberto">Aberto</option><option value="em_andamento">Em andamento</option><option value="resolvido">Resolvido</option></select></Campo><Campo nome="Ação realizada"><Textarea required minLength={3} maxLength={1000} value={texto} onChange={(e) => setTexto(e.target.value)} placeholder="Descreva a ação e a evidência que a sustenta." /></Campo></div><Button type="submit" variant="outline" disabled={acao.ocupado}><IconeDeAcao acao="criar" />Registrar ação</Button>{acao.feedback}</form>
  </article>;
}
