"""Persistencia SQL. Sem ORM: o esquema e pequeno e estavel.

DOIS DIALETOS, UM ESQUEMA. `Banco` aceita um caminho de arquivo (SQLite) ou uma
URL `postgresql://` (Supabase e qualquer outro Postgres). A escolha e do
DESTINO, nao do codigo de chamada: toda rota, todo teste e todo script
continuam falando com a mesma classe e os mesmos metodos.

POR QUE Postgres existe aqui: SQLite guarda o banco num arquivo, e host de
container com disco efemero (Render/Railway/Fly sem volume) joga esse arquivo
fora a cada deploy ou reinicio -- o cadastro de usuario "some" sem erro nenhum.
Postgres gerenciado tira a persistencia da vida do container.

O SQLite NAO foi aposentado: ele e o banco dos testes (sem servidor, sem rede,
um arquivo por teste) e do uso local. Aposentar seria trocar uma suite de
segundos por uma que exige Postgres de pe.

Latencia NAO e persistida -- e derivada dos timestamps na leitura.
"""

import json
import os
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

from fraus.modelos import Conversa
from fraus.sinais.curadoria import Curadoria

# Os tres pontos em que os dialetos de fato divergem no DDL. Ficam como
# marcador no esquema unico em vez de duas copias do arquivo inteiro: duas
# copias divergem no dia em que alguem acrescenta coluna numa so -- em silencio,
# porque nada quebra ate o outro banco ser usado.
_DIALETOS = {
    "sqlite": {
        # SQLite so autoincrementa numa coluna declarada exatamente assim.
        "SERIAL": "INTEGER PRIMARY KEY AUTOINCREMENT",
        "REAL": "REAL",
        # COLLATE NOCASE faz o proprio `=` comparar sem caixa.
        "EMAIL": "TEXT NOT NULL COLLATE NOCASE UNIQUE",
    },
    "postgres": {
        "SERIAL": "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        # REAL no Postgres e float de 4 bytes. O score e derivado de um modelo e
        # comparado com faixa; arredondar por falta de bits seria erro mudo.
        "REAL": "DOUBLE PRECISION",
        # Postgres nao tem collation sem caixa embutida -- a unicidade vira um
        # indice sobre lower(email), criado logo abaixo (ver ESQUEMA_POSTGRES).
        "EMAIL": "TEXT NOT NULL",
    },
}

ESQUEMA = """
CREATE TABLE IF NOT EXISTS conversas (
    id TEXT PRIMARY KEY,
    canal TEXT NOT NULL,
    iniciada_em TEXT NOT NULL,
    score {REAL},
    categoria TEXT,
    payload TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_conversas_iniciada_em ON conversas(iniciada_em);

-- Configuracao chave/valor JSON. A tabela guarda SO o que foi mudado: o valor
-- de fabrica vive no codigo (fraus/configuracao.py), entao banco vazio se
-- comporta exatamente como antes desta tabela existir.
CREATE TABLE IF NOT EXISTS configuracoes (
    chave TEXT PRIMARY KEY,
    valor TEXT NOT NULL
);

-- Fonte de onde conversa entra. `variavel_segredo` guarda o NOME da variavel
-- de ambiente que carrega a credencial -- NUNCA o valor. Segredo em texto puro
-- num SQLite de arquivo vaza junto com o backup.
-- `chave_hash` guarda o SHA-256 da chave de API, nunca a chave. `chave_dica`
-- sao os quatro ultimos caracteres, so para o operador reconhecer qual chave
-- esta em uso. Ver fraus/credencial.py para o porque de cada escolha.
CREATE TABLE IF NOT EXISTS fontes_integracao (
    id {SERIAL},
    nome TEXT NOT NULL,
    canal TEXT NOT NULL,
    tipo TEXT NOT NULL,
    variavel_segredo TEXT,
    ativa INTEGER NOT NULL DEFAULT 1,
    criada_em TEXT NOT NULL,
    chave_hash TEXT,
    chave_dica TEXT,
    chave_criada_em TEXT
);

-- Historico de importacao: sem ele, "importado com sucesso" e alegacao sem
-- lastro. `motivos` e o mesmo JSON que a resposta do endpoint ja devolve.
CREATE TABLE IF NOT EXISTS importacoes (
    id {SERIAL},
    ocorrida_em TEXT NOT NULL,
    arquivo TEXT NOT NULL,
    aceitas INTEGER NOT NULL,
    rejeitadas INTEGER NOT NULL,
    motivos TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_importacoes_ocorrida_em ON importacoes(ocorrida_em);

-- Chave de ACESSO: autoriza a leitura da API inteira quando FRAUS_CHAVE_MESTRA
-- esta definida. `chave_hash`/`dica` seguem o desenho de fontes_integracao:
-- hash no banco, nunca a chave; dica de 4 chars para o operador reconhecer.
-- Revogar e DELETE: chave sem linha e chave que nao autoriza.
CREATE TABLE IF NOT EXISTS chaves_acesso (
    id {SERIAL},
    nome TEXT NOT NULL,
    chave_hash TEXT,
    dica TEXT,
    criada_em TEXT NOT NULL
);

-- Chave MESTRA gravada pela tela (`POST /acesso/mestra`), a segunda procedencia
-- da mestra ao lado de FRAUS_CHAVE_MESTRA -- que continua vencendo. Existe para
-- a autenticacao ligada por botao SOBREVIVER a reiniciar o processo: mestra que
-- mora so em memoria volta a API para aberta em silencio, e "parece protegido e
-- nao esta" e a pior falha possivel aqui.
--
-- `CHECK (id = 1)` faz do "existe no maximo UMA mestra" uma garantia do banco,
-- nao uma regra que a aplicacao precisa lembrar de conferir. A chave em claro
-- nunca chega aqui: so o hash, como em toda credencial deste projeto.
CREATE TABLE IF NOT EXISTS chave_mestra (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    chave_hash TEXT NOT NULL,
    dica TEXT NOT NULL,
    criada_em TEXT NOT NULL
);

-- Usuario da DASHBOARD: identidade de quem olha a tela, nao credencial
-- tecnica -- as chaves fra_/frs_ autenticam processos e fontes e continuam
-- existindo ao lado. `senha_hash` e scrypt (ver fraus/usuarios.py), nunca a
-- senha. `papel` decide o que a pessoa PODE: 'dev' administra, 'usuario'
-- analisa -- e o CHECK faz do vocabulario garantia do banco, como o id=1 da
-- chave_mestra. `email` compara sem caixa: Ana@ e ana@ sao a mesma pessoa,
-- e tratar como duas criaria duas contas irmas.
CREATE TABLE IF NOT EXISTS usuarios (
    id {SERIAL},
    nome TEXT NOT NULL,
    email {EMAIL},
    senha_hash TEXT NOT NULL,
    papel TEXT NOT NULL CHECK (papel IN ('dev', 'usuario')),
    ativo INTEGER NOT NULL DEFAULT 1,
    criado_em TEXT NOT NULL
);

-- O que o analista ensinou ao lexico: termos que o SentiLex-PT02 e o Emoji
-- Sentiment Ranking nao trazem, ou trazem com polaridade errada para o dominio
-- de atendimento. Ver fraus/sinais/curadoria.py.
--
-- O INDICE UNICO e o que faz recadastrar o mesmo termo ser EDICAO em vez de
-- duplicata silenciosa com uma das duas vencendo por ordem de leitura.
--
-- `motivo` e opcional e existe para a decisao sobreviver a quem a tomou: um
-- peso sem porque, seis meses depois, e indistinguivel de erro de digitacao.
CREATE TABLE IF NOT EXISTS lexico_curado (
    id {SERIAL},
    tipo TEXT NOT NULL,
    termo TEXT NOT NULL,
    peso {REAL} NOT NULL,
    motivo TEXT,
    criado_em TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_lexico_curado_termo
    ON lexico_curado(tipo, termo);

-- Cada chamada de webhook, aceita ou recusada. Sem ela, um webhook recusado nao
-- deixa rastro em lugar nenhum -- e falha silenciosa e o modo de falha numero
-- um dessa integracao.
--
-- Guardar SO as recusas parece economico e quebra o diagnostico central: sem as
-- aceitas, "nao chegou nada" e "chegou e foi tudo recusado" viram a mesma tela
-- vazia.
--
-- O CORPO NUNCA ENTRA AQUI. Seria PII de cliente real parada em disco sem
-- proposito -- e o proposito de depurar e servido pelo veredito e pelo motivo.
--
-- `ON DELETE CASCADE` ao contrario das CONVERSAS, que sobrevivem a fonte:
-- entrega e registro operacional DA fonte, nao dado de atendimento medido.
CREATE TABLE IF NOT EXISTS entregas_webhook (
    id {SERIAL},
    fonte_id INTEGER NOT NULL REFERENCES fontes_integracao(id) ON DELETE CASCADE,
    webhook_id TEXT,
    recebida_em TEXT NOT NULL,
    veredito TEXT NOT NULL,
    motivo TEXT,
    conversa_id TEXT
);
CREATE INDEX IF NOT EXISTS idx_entregas_fonte ON entregas_webhook(fonte_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_entregas_dedupe ON entregas_webhook(fonte_id, webhook_id);

-- Perfil de mapeamento: qual coluna faz qual papel num export que o Fraus nao
-- conhece por nome. Confirmado uma vez pelo analista, aplicado sozinho no
-- proximo arquivo com as MESMAS colunas (a `assinatura`).
--
-- SO NOMES DE COLUNA ENTRAM AQUI, nunca celula: a amostra que o analista viu na
-- previa e dado de cliente e nao tem motivo para ficar em disco.
CREATE TABLE IF NOT EXISTS perfis_mapeamento (
    id {SERIAL},
    nome TEXT NOT NULL,
    assinatura TEXT NOT NULL,
    colunas_json TEXT NOT NULL,
    papeis_json TEXT NOT NULL,
    ordem_data TEXT,
    criado_em TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_perfis_mapeamento_assinatura
    ON perfis_mapeamento(assinatura);
"""

# Os vereditos possiveis de uma entrega, num lugar so. A tela pinta cada um de
# um jeito e a rota escolhe um deles; uma segunda lista digitada em outro
# arquivo so ficaria errada no dia em que um veredito novo entrasse -- sem erro
# nenhum, so sumindo da vista.
#
# `sem_segredo` e o unico que NAO e culpa de quem chamou: a variavel de ambiente
# da fonte sumiu do ambiente da API. Ele vira 503, nao 401.
#
# `tipo_incompativel` e a fonte que existe mas nao e do tipo `webhook`. Ele
# existe para que a recusa apareca no historico: o `tipo` ramificava so na tela,
# e uma fonte `csv` com variavel de segredo aceitava entrega assinada.
VEREDITOS = (
    "aceita",
    "assinatura",
    "fora_da_janela",
    "duplicada",
    "corpo_invalido",
    "fonte_inativa",
    "sem_segredo",
    "tipo_incompativel",
)


# O schema das tabelas no Postgres -- e a decisao de seguranca mais importante
# desta migracao.
#
# NAO e `public`. No Supabase, tudo que mora em `public` e servido pelo
# PostgREST usando a chave PUBLICAVEL -- a mesma que vai no bundle do front e
# que qualquer visitante le no DevTools. Com as tabelas em `public`, um
# `GET /rest/v1/usuarios` anonimo devolveria a coluna `senha_hash` de todo
# mundo, e `fontes_integracao.chave_hash` junto. Todo o cuidado de `_fonte` e
# `_usuario` -- que removem o hash NA ORIGEM para que esquecer de esconder seja
# impossivel -- seria contornado por uma porta que este codigo nem sabe que
# existe.
#
# Um schema proprio nao e exposto pelo PostgREST (ele so serve o que esta na
# lista `exposed_schemas`, e `fraus` nunca entra nela). Isso e defesa POR
# CONSTRUCAO: a alternativa -- deixar em `public` e ligar RLS em cada tabela --
# depende de uma politica certa por tabela, e de ninguem esquecer a proxima. O
# custo aqui e uma linha de `search_path`.
SCHEMA_POSTGRES = "fraus"

# Roda ANTES do esquema comum: as tabelas precisam do schema existindo, e do
# `search_path` apontando para ele, para nascerem no lugar certo.
ESQUEMA_POSTGRES_ANTES = f"""
CREATE SCHEMA IF NOT EXISTS {SCHEMA_POSTGRES};
SET search_path TO {SCHEMA_POSTGRES};
"""

# DDL que so o Postgres precisa, aplicado depois do esquema comum.
#
# A unicidade de e-mail SEM CAIXA e a razao de existir: no SQLite ela vem do
# `COLLATE NOCASE UNIQUE` da propria coluna, e o Postgres nao tem equivalente
# declarativo. Sem este indice, `Ana@` e `ana@` abririam DUAS contas irmas --
# exatamente o que o comentario da tabela diz que nao pode acontecer, e sem
# erro nenhum para avisar.
ESQUEMA_POSTGRES_EXTRA = """
CREATE UNIQUE INDEX IF NOT EXISTS idx_usuarios_email_sem_caixa
    ON usuarios (lower(email));
"""


def _traduzir(sql: str) -> str:
    """Marcador posicional do SQLite (`?`) para o do psycopg (`%s`).

    Substituicao direta, e nao um parser: nenhuma consulta deste arquivo tem
    `?` ou `%` dentro de literal de texto -- todo valor entra por parametro,
    que e a mesma regra que ja impede injecao aqui. Se um dia entrar, este e o
    ponto que precisa ficar mais esperto.
    """
    return sql.replace("?", "%s")


class _ConexaoSqlite:
    """Conexao SQLite que de fato FECHA ao sair do `with`.

    `with sqlite3.connect(...)` faz commit e NAO fecha -- e uma pegadinha da
    biblioteca padrao. Como este modulo abre uma conexao POR CHAMADA, cada
    metodo deixava um descritor aberto para o coletor recolher quando desse na
    telha.

    Em Linux passa despercebido. No Windows o arquivo fica TRAVADO: apagar o
    diretorio temporario de um teste levanta `PermissionError [WinError 32]`.
    Foi assim que o defeito apareceu -- dois scripts diferentes quebraram no
    mesmo ponto antes de alguem procurar a causa.

    Existe tambem para emparelhar com `_ConexaoPostgres`: la o `__exit__`
    devolve a conexao ao pool, e ter um dialeto que solta o recurso e outro que
    nao solta e a assimetria que vira bug quando alguem le um caminho e assume
    o outro.
    """

    def __init__(self, conexao: sqlite3.Connection) -> None:
        self._conexao = conexao

    def execute(self, sql: str, parametros=()):
        return self._conexao.execute(sql, parametros)

    def executemany(self, sql: str, sequencia):
        return self._conexao.executemany(sql, sequencia)

    def executescript(self, sql: str):
        return self._conexao.executescript(sql)

    def __enter__(self) -> "_ConexaoSqlite":
        return self

    def __exit__(self, tipo, valor, traco) -> None:
        # Commit no caminho feliz e rollback no erro -- o mesmo contrato que o
        # `with` do sqlite3 ja dava e que todo metodo daqui assume. O `finally`
        # garante que a conexao fecha inclusive quando o proprio commit falha.
        try:
            if tipo is None:
                self._conexao.commit()
            else:
                self._conexao.rollback()
        finally:
            self._conexao.close()


class _ConexaoPostgres:
    """Conexao Postgres com a MESMA superficie que o codigo ja usava do SQLite.

    Existe para que os ~40 metodos abaixo continuem escritos em um dialeto so.
    A alternativa -- um `if self._postgres` dentro de cada metodo -- dobraria
    cada consulta e faria os dois caminhos divergirem no primeiro dia em que
    alguem mexesse em um sem lembrar do outro.

    O `?` vira `%s` na entrada, e `execute`/`executemany`/`fetchone` seguem
    devolvendo cursor e dicionario como antes.
    """

    def __init__(self, conexao) -> None:
        self._conexao = conexao

    def execute(self, sql: str, parametros=()):
        return self._conexao.execute(_traduzir(sql), parametros)

    def executemany(self, sql: str, sequencia):
        cursor = self._conexao.cursor()
        cursor.executemany(_traduzir(sql), list(sequencia))
        return cursor

    def executescript(self, sql: str) -> None:
        """DDL de varios comandos. O psycopg aceita direto, sem parametro."""
        self._conexao.execute(sql)

    def __enter__(self) -> "_ConexaoPostgres":
        return self

    def __exit__(self, tipo, valor, traco) -> None:
        # Commit no caminho feliz, rollback no erro -- o mesmo contrato do
        # `with` do sqlite3, que todo metodo daqui ja assumia. Devolver a
        # conexao ao pool e o extra: sem isso, cada chamada abriria um TLS novo
        # contra o Supabase e o pool secaria em poucas requisicoes.
        if tipo is None:
            self._conexao.commit()
        else:
            self._conexao.rollback()
        self._devolver()

    def _devolver(self) -> None:
        self._contexto.__exit__(None, None, None)


# Erro de unicidade violada, no dialeto que estiver em uso. A borda HTTP captura
# ISTO, nunca `sqlite3.IntegrityError` direto -- `POST /auth/registrar` traduz em
# 409, e no Postgres o e-mail duplicado levantaria uma classe que aquele `except`
# nao pegaria: o cadastro viraria 500 em vez de "ja existe uma conta".
ErroDeIntegridade: tuple[type[Exception], ...] = (sqlite3.IntegrityError,)

try:  # pragma: no cover - depende do extra de Postgres estar instalado
    import psycopg

    ErroDeIntegridade = (sqlite3.IntegrityError, psycopg.errors.IntegrityError)
except ImportError:  # pragma: no cover
    psycopg = None


class Banco:
    """Aceita um caminho de arquivo (SQLite) ou uma URL `postgresql://`."""

    def __init__(self, destino: "Path | str") -> None:
        texto = str(destino)
        self._postgres = texto.startswith(("postgres://", "postgresql://"))
        self._url = texto if self._postgres else None
        self._caminho = None if self._postgres else Path(destino)
        self._pool = None
        if self._postgres and psycopg is None:
            raise RuntimeError(
                "FRAUS_DATABASE_URL aponta para Postgres mas o psycopg nao esta "
                "instalado. Rode `uv sync` (a dependencia entrou no pyproject)."
            )

    @property
    def dialeto(self) -> str:
        return "postgres" if self._postgres else "sqlite"

    def _obter_pool(self):
        """Pool criado na primeira consulta, nao no __init__.

        `Banco(url)` e construido no boot e tambem em teste; abrir conexao no
        construtor faria montar o objeto exigir o banco de pe, e o `criar_app`
        depende de poder falhar por modelo ausente ANTES de tocar no banco.
        """
        if self._pool is None:
            from psycopg.rows import dict_row
            from psycopg_pool import ConnectionPool

            self._pool = ConnectionPool(
                self._url,
                min_size=1,
                # O teto e do POOLER do Supabase, nao nosso: o plano gratuito da
                # poucas conexoes, e estourar derruba a API inteira com "too
                # many clients" em vez de so ficar lento.
                max_size=int(os.environ.get("FRAUS_POSTGRES_MAX_CONEXOES", "5")),
                # `prepare_threshold=None` desliga o prepared statement do
                # psycopg. O pooler do Supabase em modo TRANSACTION (porta 6543)
                # entrega uma sessao diferente a cada transacao, e um statement
                # preparado na sessao anterior nao existe na seguinte -- o erro
                # aparece so depois de algumas chamadas, o que e pior que
                # aparecer sempre.
                kwargs={
                    "row_factory": dict_row,
                    "prepare_threshold": None,
                    # `search_path` na CONEXAO, e nao tabela por tabela nas ~40
                    # consultas abaixo: prefixar cada uma daria o mesmo
                    # resultado hoje e falharia na primeira consulta nova que
                    # alguem escrevesse sem lembrar do prefixo -- caindo em
                    # `public`, onde o PostgREST serve. Aqui, esquecer nao e
                    # uma opcao disponivel.
                    "options": f"-c search_path={SCHEMA_POSTGRES}",
                },
                open=True,
            )
        return self._pool

    def _conectar(self):
        if self._postgres:
            contexto = self._obter_pool().connection()
            conexao = _ConexaoPostgres(contexto.__enter__())
            conexao._contexto = contexto
            return conexao
        conexao = sqlite3.connect(self._caminho)
        conexao.row_factory = sqlite3.Row
        # SQLite ignora chave estrangeira por padrao, e o pragma vale por
        # CONEXAO -- ligar uma vez na criacao do esquema nao teria efeito
        # nenhum nas seguintes. Sem isto, o ON DELETE CASCADE de
        # `entregas_webhook` seria documentacao, nao comportamento: apagar a
        # fonte deixaria as entregas orfas apontando para um id que ninguem
        # mais consegue consultar.
        conexao.execute("PRAGMA foreign_keys = ON")
        return _ConexaoSqlite(conexao)

    def _ordem(self, coluna: str) -> str:
        """Ordenacao de coluna TEXT com data ISO, IGUAL nos dois dialetos.

        AS DATAS DESTE BANCO SAO TEXTO. Isso funciona porque ISO-8601 em UTC
        ordena igual lexicograficamente -- mas so quando a comparacao e por
        BYTE, e o Postgres do Supabase nao compara por byte.

        O banco nasce com `datcollate = en_US.UTF-8`, e essa collation ignora
        pontuacao no nivel primario. Medido no banco de producao:

            '2026-03-01T10:00:00+00:00' < '2026-03-01T10:00:00.500000+00:00'
              Python/SQLite ....... True
              Postgres padrao ..... False   <-- o ponto e ignorado
              Postgres COLLATE C .. True

        `datetime.now(timezone.utc).isoformat()` sempre carrega microssegundos,
        entao basta UMA conversa com fracao de segundo para a listagem sair
        fora de ordem -- e SO em producao. A suite roda em SQLite e nunca ve.
        Foi uma regressao da migracao de 02/09/2026: a mesma consulta passou a
        significar coisas diferentes nos dois bancos.

        `COLLATE "C"` e a collation de BYTE do Postgres, que e exatamente o que
        o SQLite ja fazia. Ela vai na CLAUSULA DE ORDENACAO e nao na coluna, de
        proposito: mudar o tipo da coluna exigiria migrar a tabela, e o que
        precisa ser bytewise e a comparacao, nao o armazenamento.
        """
        return f'{coluna} COLLATE "C"' if self._postgres else coluna

    def _upsert(self, tabela: str, colunas: tuple[str, ...], chaves: tuple[str, ...]) -> str:
        """`INSERT OR REPLACE` do SQLite e o `ON CONFLICT` equivalente no Postgres.

        Sao equivalentes AQUI porque todo chamador lista a linha inteira: o
        `REPLACE` do SQLite apaga e reinsere (zerando coluna omitida), e o
        `DO UPDATE` so mexe no que foi nomeado -- sem coluna omitida, o
        resultado e o mesmo nos dois.
        """
        marcadores = ", ".join("?" for _ in colunas)
        lista = ", ".join(colunas)
        if not self._postgres:
            return f"INSERT OR REPLACE INTO {tabela} ({lista}) VALUES ({marcadores})"
        atualiza = ", ".join(
            f"{coluna} = EXCLUDED.{coluna}" for coluna in colunas if coluna not in chaves
        )
        return (
            f"INSERT INTO {tabela} ({lista}) VALUES ({marcadores}) "
            f"ON CONFLICT ({', '.join(chaves)}) DO UPDATE SET {atualiza}"
        )

    def _inserir(self, conexao, sql: str, parametros: tuple) -> int:
        """Insere e devolve o id gerado, no dialeto em uso.

        `lastrowid` e do SQLite; o Postgres responde por `RETURNING id`. Os dois
        chamadores precisam do id na hora -- a chave de acesso e a de fonte
        EMBUTEM o id no segredo que geram.
        """
        if self._postgres:
            return conexao.execute(f"{sql} RETURNING id", parametros).fetchone()["id"]
        return conexao.execute(sql, parametros).lastrowid

    # Colunas acrescentadas depois que a tabela ja existia em disco.
    # `CREATE TABLE IF NOT EXISTS` cria o banco novo com elas e nao faz nada
    # num banco antigo -- que continuaria sem as colunas e quebraria na leitura.
    COLUNAS_ACRESCENTADAS = (
        ("fontes_integracao", "chave_hash", "TEXT"),
        ("fontes_integracao", "chave_dica", "TEXT"),
        ("fontes_integracao", "chave_criada_em", "TEXT"),
        ("conversas", "lexico_versao", "INTEGER"),
    )

    def migrar(self) -> None:
        dialeto = _DIALETOS[self.dialeto]
        with self._conectar() as conexao:
            if self._postgres:
                conexao.executescript(ESQUEMA_POSTGRES_ANTES)
            conexao.executescript(ESQUEMA.format(**dialeto))
            if self._postgres:
                conexao.executescript(ESQUEMA_POSTGRES_EXTRA)
            for tabela, coluna, tipo in self.COLUNAS_ACRESCENTADAS:
                if self._postgres:
                    # O Postgres tem a forma declarativa; o SQLite nao, e por
                    # isso o caminho abaixo existe.
                    conexao.execute(
                        f"ALTER TABLE {tabela} ADD COLUMN IF NOT EXISTS {coluna} {tipo}"
                    )
                    continue
                existentes = {
                    linha["name"]
                    for linha in conexao.execute(f"PRAGMA table_info({tabela})")
                }
                if coluna not in existentes:
                    conexao.execute(f"ALTER TABLE {tabela} ADD COLUMN {coluna} {tipo}")

    def salvar(
        self,
        conversa: Conversa,
        score: float | None,
        categoria: str | None,
        lexico_versao: int | None = None,
    ) -> None:
        """Grava a conversa e COM QUAL LEXICO ela foi pontuada.

        `lexico_versao` e opcional e vai ao fim porque todo chamador anterior a
        curadoria continua valendo -- e `None` ali significa exatamente o que
        significa numa linha de banco antigo: nao se sabe, logo defasada.
        """
        with self._conectar() as conexao:
            conexao.execute(
                self._upsert(
                    "conversas",
                    ("id", "canal", "iniciada_em", "score", "categoria", "payload",
                     "lexico_versao"),
                    ("id",),
                ),
                (
                    conversa.id,
                    conversa.canal,
                    conversa.iniciada_em.isoformat(),
                    score,
                    categoria,
                    conversa.model_dump_json(),
                    lexico_versao,
                ),
            )

    def listar(self) -> list[dict]:
        with self._conectar() as conexao:
            linhas = conexao.execute(
                "SELECT id, canal, iniciada_em, score, categoria FROM conversas "
                f"ORDER BY {self._ordem('iniciada_em')} DESC"
            ).fetchall()
        return [dict(linha) for linha in linhas]

    def listar_com_conversa(self) -> list[tuple[dict, Conversa]]:
        """Como `listar`, mas trazendo a conversa inteira junto de cada linha.

        Existe para a lista de atendimentos poder mostrar tempo de resposta,
        contagem de mensagens e desfecho -- coisas que so o `payload` sabe. A
        alternativa era o cliente pedir `/conversas/{id}` de cada linha, um
        N+1 que a dashboard ja pagou caro em outras telas.

        Os agregados sao DERIVADOS na leitura, nunca gravados em coluna. Coluna
        denormalizada envelheceria em silencio no dia em que a regra de
        latencia mudasse, e a tabela passaria a exibir um numero que o resto do
        sistema nao reconhece mais. O custo e ler e desserializar o JSON de
        todas as conversas do recorte -- aceitavel na ordem de grandeza deste
        projeto (milhares), e o ponto a trocar por uma materializacao se um dia
        deixar de ser.
        """
        with self._conectar() as conexao:
            linhas = conexao.execute(
                "SELECT id, canal, iniciada_em, score, categoria, payload FROM conversas "
                f"ORDER BY {self._ordem('iniciada_em')} DESC"
            ).fetchall()
        return [
            (
                {
                    chave: linha[chave]
                    for chave in ("id", "canal", "iniciada_em", "score", "categoria")
                },
                Conversa(**json.loads(linha["payload"])),
            )
            for linha in linhas
        ]

    def buscar(self, conversa_id: str) -> tuple[Conversa, float | None, str | None] | None:
        with self._conectar() as conexao:
            linha = conexao.execute(
                "SELECT payload, score, categoria FROM conversas WHERE id = ?", (conversa_id,)
            ).fetchone()
        if linha is None:
            return None
        return Conversa(**json.loads(linha["payload"])), linha["score"], linha["categoria"]

    def ler_configuracoes(self) -> dict:
        """So o que foi de fato alterado. O padrao de fabrica nao mora no banco."""
        with self._conectar() as conexao:
            linhas = conexao.execute("SELECT chave, valor FROM configuracoes").fetchall()
        return {linha["chave"]: json.loads(linha["valor"]) for linha in linhas}

    def escrever_configuracoes(self, valores: dict) -> None:
        """Grava as chaves recebidas numa transacao so -- meia configuracao seria pior."""
        with self._conectar() as conexao:
            conexao.executemany(
                self._upsert("configuracoes", ("chave", "valor"), ("chave",)),
                [(chave, json.dumps(valor)) for chave, valor in valores.items()],
            )

    def criar_fonte(
        self, nome: str, canal: str, tipo: str, variavel_segredo: str | None, criada_em: str
    ) -> dict:
        with self._conectar() as conexao:
            identificador = self._inserir(
                conexao,
                "INSERT INTO fontes_integracao "
                "(nome, canal, tipo, variavel_segredo, ativa, criada_em) VALUES (?, ?, ?, ?, 1, ?)",
                (nome, canal, tipo, variavel_segredo, criada_em),
            )
        return self.buscar_fonte(identificador)

    def listar_fontes(self) -> list[dict]:
        with self._conectar() as conexao:
            linhas = conexao.execute(
                f"SELECT * FROM fontes_integracao ORDER BY {self._ordem('criada_em')}, id"
            ).fetchall()
        return [self._fonte(linha) for linha in linhas]

    def buscar_fonte(self, identificador: int) -> dict | None:
        with self._conectar() as conexao:
            linha = conexao.execute(
                "SELECT * FROM fontes_integracao WHERE id = ?", (identificador,)
            ).fetchone()
        return self._fonte(linha) if linha is not None else None

    def atualizar_fonte(
        self, identificador: int, nome: str | None = None, ativa: bool | None = None
    ) -> dict | None:
        campos, valores = [], []
        if nome is not None:
            campos.append("nome = ?")
            valores.append(nome)
        if ativa is not None:
            campos.append("ativa = ?")
            valores.append(1 if ativa else 0)
        if campos:
            with self._conectar() as conexao:
                conexao.execute(
                    f"UPDATE fontes_integracao SET {', '.join(campos)} WHERE id = ?",
                    (*valores, identificador),
                )
        return self.buscar_fonte(identificador)

    def hash_da_chave_da_fonte(self, identificador: int) -> str | None:
        """O unico caminho para ler o hash. Explicito no nome e de uso unico.

        Existe separado de `buscar_fonte` para que o hash nunca viaje dentro do
        dicionario que a API serializa -- ver `_fonte`.
        """
        with self._conectar() as conexao:
            linha = conexao.execute(
                "SELECT chave_hash FROM fontes_integracao WHERE id = ?", (identificador,)
            ).fetchone()
        return linha["chave_hash"] if linha is not None else None

    def gravar_chave(
        self, identificador: int, chave_hash: str, dica: str, criada_em: str
    ) -> dict | None:
        """Grava a chave nova SUBSTITUINDO a anterior.

        Uma chave ativa por fonte, sempre. Duas chaves validas ao mesmo tempo
        dariam a impressao de rotacao sem risco, mas a antiga continuaria
        aceita e ninguem saberia quem ainda a usa -- gerar uma chave tem que
        invalidar a de antes, para "gerei outra" significar de fato que a
        anterior parou de funcionar.
        """
        with self._conectar() as conexao:
            conexao.execute(
                "UPDATE fontes_integracao "
                "SET chave_hash = ?, chave_dica = ?, chave_criada_em = ? WHERE id = ?",
                (chave_hash, dica, criada_em, identificador),
            )
        return self.buscar_fonte(identificador)

    def revogar_chave(self, identificador: int) -> dict | None:
        """Apaga a chave da fonte. A fonte e o historico dela continuam."""
        with self._conectar() as conexao:
            conexao.execute(
                "UPDATE fontes_integracao "
                "SET chave_hash = NULL, chave_dica = NULL, chave_criada_em = NULL "
                "WHERE id = ?",
                (identificador,),
            )
        return self.buscar_fonte(identificador)

    def apagar_fonte(self, identificador: int) -> bool:
        """Remove SO o cadastro da fonte. Nenhuma conversa e tocada aqui.

        Conversa que ja entrou e dado do atendimento, nao propriedade da fonte:
        apagar a origem nao pode reescrever o historico de satisfacao medido.
        """
        with self._conectar() as conexao:
            cursor = conexao.execute(
                "DELETE FROM fontes_integracao WHERE id = ?", (identificador,)
            )
            return cursor.rowcount > 0

    # Quantas entregas cada fonte guarda EM CADA BALDE. Registrar recusa de
    # assinatura e exatamente o que o operador precisa ver -- alguem esta
    # batendo com o segredo errado -- e e tambem como um atacante enche o
    # banco. A poda e o que permite manter a primeira propriedade sem pagar a
    # segunda.
    #
    # SAO DOIS BALDES, aceitas e o resto, e isto e conserto de 03/09/2026. Antes
    # a poda nao distinguia veredito, e as duas coisas disputavam as mesmas 200
    # vagas. Como a rota de webhook e isenta de chave de acesso por desenho -- a
    # plataforma externa nao tem como carregar uma `fra_` --, 210 requisicoes
    # anonimas com assinatura lixo zeravam as aceitas de uma fonte. Reproduzido
    # em 02/09/2026.
    #
    # O dano nao era so o historico: esta tabela e TAMBEM a memoria do dedupe
    # (`entrega_ja_vista`), entao apagar as aceitas fazia reentrega legitima
    # voltar a ser processada como nova. O comentario antigo aqui dizia que o
    # efeito era "limitado" porque `salvar` usa INSERT OR REPLACE e reprocessar
    # so repontua -- verdade para o dado, falsa para o custo: reprocessar e
    # inferencia de BERTimbau, e era um anonimo quem decidia quando ela roda.
    #
    # Dois baldes, e nao um por veredito: por veredito o teto viraria
    # 200 x len(VEREDITOS) e cresceria sozinho toda vez que alguem acrescentasse
    # um motivo de recusa. Aqui o teto por fonte e 2 x ENTREGAS_POR_FONTE, fixo.
    ENTREGAS_POR_FONTE = 200

    def registrar_entrega(
        self,
        fonte_id: int,
        webhook_id: str | None,
        veredito: str,
        recebida_em: str,
        motivo: str | None = None,
        conversa_id: str | None = None,
    ) -> None:
        """Registra a tentativa e poda as antigas DAQUELA fonte, numa transacao.

        A poda anda junto com o insert de proposito: separada, ela dependeria de
        alguem lembrar de chama-la, e o dia em que ninguem lembrasse seria o dia
        em que a tabela cresce sem teto.
        """
        with self._conectar() as conexao:
            conexao.execute(
                "INSERT INTO entregas_webhook "
                "(fonte_id, webhook_id, recebida_em, veredito, motivo, conversa_id) "
                "VALUES (?, ?, ?, ?, ?, ?)",
                (fonte_id, webhook_id, recebida_em, veredito, motivo, conversa_id),
            )
            # O corte usa o MESMO criterio de `listar_entregas`
            # (`recebida_em DESC, id DESC`), de proposito: `recebida_em` e
            # carimbado pelo servidor no instante em que a chamada chega (a
            # rota grava `datetime.now(timezone.utc)`, nunca um campo do
            # corpo) -- e tao interno quanto o `id`, entao nao ha razao para
            # os dois criterios divergirem. Com o mesmo criterio nos dois
            # lados, "as 200 que ficam" e "as 200 que aparecem" sao
            # literalmente o mesmo conjunto, na mesma ordem, por construcao.
            # `id` entra so como desempate, porque duas entregas podem
            # carimbar o mesmo instante ISO.
            #
            # OS DOIS BALDES sao selecionados separadamente e reunidos por
            # UNION ALL: cada um preserva as suas N mais recentes, e nenhum pode
            # despejar o outro. O `SELECT id FROM (...)` externo existe porque
            # nem SQLite nem Postgres aceitam LIMIT direto num operando de UNION.
            mais_recentes = (
                "SELECT id FROM (SELECT id FROM entregas_webhook "
                "WHERE fonte_id = ? AND veredito {comparador} 'aceita' "
                f"ORDER BY {self._ordem('recebida_em')} DESC, id DESC LIMIT ?) AS _{{apelido}}"
            )
            conexao.execute(
                "DELETE FROM entregas_webhook WHERE fonte_id = ? AND id NOT IN ("
                + mais_recentes.format(comparador="=", apelido="aceitas")
                + " UNION ALL "
                + mais_recentes.format(comparador="<>", apelido="recusadas")
                + ")",
                (
                    fonte_id,
                    fonte_id, self.ENTREGAS_POR_FONTE,
                    fonte_id, self.ENTREGAS_POR_FONTE,
                ),
            )

    def listar_entregas(self, fonte_id: int) -> list[dict]:
        """Entregas da fonte, mais recente primeiro.

        Ordena por `recebida_em` -- o horario que a chamada de fato chegou --
        com `id` como desempate. So por `id` colocaria a ordem de insercao na
        frente do horario real quando as duas divergem (ex.: reprocessamento
        fora de ordem), e e o horario que o operador espera ver no topo.
        """
        with self._conectar() as conexao:
            linhas = conexao.execute(
                "SELECT id, fonte_id, webhook_id, recebida_em, veredito, motivo, "
                "conversa_id FROM entregas_webhook WHERE fonte_id = ? "
                f"ORDER BY {self._ordem('recebida_em')} DESC, id DESC",
                (fonte_id,),
            ).fetchall()
        return [dict(linha) for linha in linhas]

    def entrega_ja_vista(self, fonte_id: int, webhook_id: str) -> bool:
        """Se aquele evento ja foi ACEITO por aqui. O dedupe e POR FONTE.

        Duas plataformas podem numerar eventos igual, e tratar o `msg_1` de uma
        como reentrega da outra descartaria atendimento em silencio.

        So conta veredito "aceita" -- de proposito. Uma RECUSA registrada
        (assinatura errada, variavel de ambiente ausente, fonte desativada) nao
        e uma entrega ja processada, e uma tentativa. Contar qualquer veredito
        aqui abre duas portas: um anonimo manda `webhook-id` alheio com
        assinatura lixo so para "queimar" aquele id antes da plataforma
        legitima entregar (a rota e ISENTA de chave de acesso, e o formato do
        id costuma ser previsivel); e, sem atacante nenhum, um operador que
        corrige a variavel de ambiente ou reativa a fonte depois de um 503/403
        veria a propria retentativa cair como "duplicada" e o atendimento se
        perder para sempre -- exatamente o caminho de recuperacao que a
        integracao existe para oferecer.
        """
        with self._conectar() as conexao:
            linha = conexao.execute(
                "SELECT 1 FROM entregas_webhook WHERE fonte_id = ? AND webhook_id = ? "
                "AND veredito = 'aceita' LIMIT 1",
                (fonte_id, webhook_id),
            ).fetchone()
        return linha is not None

    @staticmethod
    def _fonte(linha: sqlite3.Row) -> dict:
        """Fonte como ela pode circular. O HASH DA CHAVE NAO SAI POR AQUI.

        O `chave_hash` e removido neste unico ponto, e nao na borda HTTP, de
        proposito: `_fonte_publica` monta a resposta com `{**fonte}`, entao
        qualquer coluna nova da tabela apareceria sozinha na API sem ninguem
        decidir isso. Tirando o campo na origem, esquecer de esconder deixa de
        ser possivel -- quem precisa dele chama `hash_da_chave_da_fonte`, que e
        explicito no nome e no uso.

        O hash nao e senha e nem por isso pode circular: ele e o suficiente
        para confirmar um palpite de chave offline, sem nenhuma requisicao.
        """
        registro = dict(linha)
        registro["ativa"] = bool(registro["ativa"])
        registro.pop("chave_hash", None)
        return registro

    def registrar_importacao(
        self, ocorrida_em: str, arquivo: str, aceitas: int, rejeitadas: int, motivos: list[dict]
    ) -> None:
        with self._conectar() as conexao:
            conexao.execute(
                "INSERT INTO importacoes (ocorrida_em, arquivo, aceitas, rejeitadas, motivos) "
                "VALUES (?, ?, ?, ?, ?)",
                (ocorrida_em, arquivo, aceitas, rejeitadas, json.dumps(motivos)),
            )

    def listar_importacoes(self) -> list[dict]:
        with self._conectar() as conexao:
            linhas = conexao.execute(
                f"SELECT * FROM importacoes ORDER BY {self._ordem('ocorrida_em')} DESC, id DESC"
            ).fetchall()
        return [{**dict(l), "motivos": json.loads(l["motivos"])} for l in linhas]

    def todas(self) -> list[tuple[Conversa, float | None]]:
        with self._conectar() as conexao:
            linhas = conexao.execute("SELECT payload, score FROM conversas").fetchall()
        return [(Conversa(**json.loads(l["payload"])), l["score"]) for l in linhas]

    def criar_chave_acesso(self, nome: str, criada_em: str) -> dict:
        """Cria a LINHA da chave. O hash chega depois, por gravar_chave_acesso:
        a chave embute o id, entao o id precisa existir antes do segredo."""
        with self._conectar() as conexao:
            identificador = self._inserir(
                conexao,
                "INSERT INTO chaves_acesso (nome, criada_em) VALUES (?, ?)",
                (nome, criada_em),
            )
        return {"id": identificador, "nome": nome, "dica": None, "criada_em": criada_em}

    def gravar_chave_acesso(self, identificador: int, chave_hash: str, dica: str) -> None:
        with self._conectar() as conexao:
            conexao.execute(
                "UPDATE chaves_acesso SET chave_hash = ?, dica = ? WHERE id = ?",
                (chave_hash, dica, identificador),
            )

    def listar_chaves_acesso(self) -> list[dict]:
        """O HASH NAO SAI POR AQUI -- mesma regra de _fonte: removido na origem."""
        with self._conectar() as conexao:
            linhas = conexao.execute(
                f"SELECT id, nome, dica, criada_em FROM chaves_acesso ORDER BY {self._ordem('criada_em')}, id"
            ).fetchall()
        return [dict(linha) for linha in linhas]

    def hash_da_chave_acesso(self, identificador: int) -> str | None:
        """O unico caminho para ler o hash -- explicito no nome, uso unico."""
        with self._conectar() as conexao:
            linha = conexao.execute(
                "SELECT chave_hash FROM chaves_acesso WHERE id = ?", (identificador,)
            ).fetchone()
        return linha["chave_hash"] if linha is not None else None

    def apagar_chave_acesso(self, identificador: int) -> bool:
        with self._conectar() as conexao:
            cursor = conexao.execute(
                "DELETE FROM chaves_acesso WHERE id = ?", (identificador,)
            )
            return cursor.rowcount > 0

    @staticmethod
    def _usuario(linha: sqlite3.Row) -> dict:
        """Usuario como ele pode circular. O HASH DA SENHA NAO SAI POR AQUI --
        mesma regra de `_fonte`: removido na origem, nao na borda HTTP."""
        registro = dict(linha)
        registro["ativo"] = bool(registro["ativo"])
        registro.pop("senha_hash", None)
        return registro

    def criar_usuario(
        self, nome: str, email: str, senha_hash: str, papel: str, criado_em: str
    ) -> dict:
        """E-mail duplicado deixa o IntegrityError propagar: a unicidade e
        garantia do banco, e a borda HTTP traduz em 409 -- o mesmo desenho da
        coluna ausente no driver de CSV."""
        with self._conectar() as conexao:
            identificador = self._inserir(
                conexao,
                "INSERT INTO usuarios (nome, email, senha_hash, papel, criado_em) "
                "VALUES (?, ?, ?, ?, ?)",
                (nome, email, senha_hash, papel, criado_em),
            )
        return {
            "id": identificador,
            "nome": nome,
            "email": email,
            "papel": papel,
            "ativo": True,
            "criado_em": criado_em,
        }

    def buscar_usuario(self, identificador: int) -> dict | None:
        with self._conectar() as conexao:
            linha = conexao.execute(
                "SELECT * FROM usuarios WHERE id = ?", (identificador,)
            ).fetchone()
        return self._usuario(linha) if linha is not None else None

    def buscar_usuario_por_email(self, email: str) -> dict | None:
        # No SQLite a coluna e COLLATE NOCASE e o proprio `=` ja compara sem
        # caixa. No Postgres a comparacao precisa ser explicita -- e ela usa a
        # MESMA expressao do indice unico (`lower(email)`), de proposito: se as
        # duas divergissem, o banco recusaria o cadastro duplicado que a busca
        # nao acha, e o login diria "e-mail invalido" para uma conta existente.
        consulta = (
            "SELECT * FROM usuarios WHERE lower(email) = lower(?)"
            if self._postgres
            else "SELECT * FROM usuarios WHERE email = ?"
        )
        with self._conectar() as conexao:
            linha = conexao.execute(consulta, (email,)).fetchone()
        return self._usuario(linha) if linha is not None else None

    def hash_da_senha(self, identificador: int) -> str | None:
        """O unico caminho para ler o hash -- explicito no nome, uso unico."""
        with self._conectar() as conexao:
            linha = conexao.execute(
                "SELECT senha_hash FROM usuarios WHERE id = ?", (identificador,)
            ).fetchone()
        return linha["senha_hash"] if linha is not None else None

    def gravar_chave_mestra(self, chave_hash: str, dica: str, criada_em: str) -> None:
        """Grava a mestra NO LUGAR da anterior, se houver.

        `INSERT OR REPLACE` com `id = 1` fixo: a rotacao TROCA a credencial em
        vez de acumular uma segunda valida -- duas mestras aceitas ao mesmo
        tempo pareceriam rotacao sem risco, mas a antiga seguiria autorizando
        sem ninguem saber quem ainda a usa.
        """
        with self._conectar() as conexao:
            conexao.execute(
                self._upsert(
                    "chave_mestra", ("id", "chave_hash", "dica", "criada_em"), ("id",)
                ),
                (1, chave_hash, dica, criada_em),
            )

    def hash_da_chave_mestra(self) -> str | None:
        """O unico caminho para ler o hash da mestra -- explicito no nome."""
        with self._conectar() as conexao:
            linha = conexao.execute(
                "SELECT chave_hash FROM chave_mestra WHERE id = 1"
            ).fetchone()
        return linha["chave_hash"] if linha is not None else None

    def apagar_chave_mestra(self) -> bool:
        """Remove a mestra do banco. Devolve se havia alguma para remover.

        NAO existe rota que chame isto, e a ausencia e a decisao: desligar a
        autenticacao pela rede seria uma chamada que baixa a defesa, e a API
        pode estar aberta justamente quando ela e feita. O unico chamador e
        `scripts/resetar_mestra.py`, que exige o disco e a mao de quem opera --
        e e a saida para quem perdeu a chave gerada pela tela.

        A autenticacao e decidida POR REQUISICAO, entao o efeito vale na
        chamada seguinte, sem reiniciar a API.
        """
        with self._conectar() as conexao:
            cursor = conexao.execute("DELETE FROM chave_mestra WHERE id = 1")
            return cursor.rowcount > 0

    def chave_mestra_registrada(self) -> dict | None:
        """Dica e data da mestra gravada. O HASH NAO SAI POR AQUI.

        `None` quando nao ha mestra no banco -- que e diferente de "nao ha
        mestra": a do ambiente nao passa por esta tabela.
        """
        with self._conectar() as conexao:
            linha = conexao.execute(
                "SELECT dica, criada_em FROM chave_mestra WHERE id = 1"
            ).fetchone()
        if linha is None:
            return None
        return {"dica": linha["dica"], "criada_em": linha["criada_em"]}

    # ---- lexico curado --------------------------------------------------

    # A versao mora na tabela de configuracoes, e nao numa tabela propria: ela e
    # UM inteiro, e a tabela chave/valor existe exatamente para isso. Comeca em
    # 0 e sobe a cada ESCRITA -- curar e revogar contam igual, porque as duas
    # mudam o que o lexico responde.
    CHAVE_VERSAO = "lexico_versao"

    def lexico_versao(self) -> int:
        with self._conectar() as conexao:
            linha = conexao.execute(
                "SELECT valor FROM configuracoes WHERE chave = ?", (self.CHAVE_VERSAO,)
            ).fetchone()
        return int(json.loads(linha["valor"])) if linha else 0

    def _incrementar_versao(self, conexao) -> int:
        """Sobe a versao DENTRO da transacao de quem chamou.

        Recebe a conexao em vez de abrir a propria: gravar o termo e subir a
        versao precisam acontecer juntos ou nenhum dos dois. Em transacoes
        separadas, uma falha no meio deixaria termo curado com versao antiga --
        e a tela diria que o banco esta em dia quando nao esta.
        """
        linha = conexao.execute(
            "SELECT valor FROM configuracoes WHERE chave = ?", (self.CHAVE_VERSAO,)
        ).fetchone()
        proxima = (int(json.loads(linha["valor"])) if linha else 0) + 1
        conexao.execute(
            self._upsert("configuracoes", ("chave", "valor"), ("chave",)),
            (self.CHAVE_VERSAO, json.dumps(proxima)),
        )
        return proxima

    def curar(self, tipo: str, termo: str, peso: float, motivo: str | None) -> dict:
        """Cadastra ou EDITA um termo curado. Devolve o registro gravado."""
        agora = datetime.now(timezone.utc).isoformat()
        with self._conectar() as conexao:
            conexao.execute(
                "INSERT INTO lexico_curado (tipo, termo, peso, motivo, criado_em) "
                "VALUES (?, ?, ?, ?, ?) "
                "ON CONFLICT(tipo, termo) DO UPDATE SET "
                "peso = excluded.peso, motivo = excluded.motivo, "
                "criado_em = excluded.criado_em",
                (tipo, termo, peso, motivo, agora),
            )
            self._incrementar_versao(conexao)
            linha = conexao.execute(
                "SELECT * FROM lexico_curado WHERE tipo = ? AND termo = ?",
                (tipo, termo),
            ).fetchone()
        return dict(linha)

    @staticmethod
    def _perfil(linha) -> dict:
        registro = dict(linha)
        registro["colunas"] = json.loads(registro.pop("colunas_json"))
        registro["papeis"] = json.loads(registro.pop("papeis_json"))
        return registro

    def salvar_perfil_mapeamento(
        self,
        nome: str,
        assinatura: str,
        colunas: list[str],
        papeis: dict[str, str | None],
        ordem_data: str | None,
    ) -> dict:
        """Cria ou EDITA pela assinatura -- a mesma estrutura tem um perfil so."""
        agora = datetime.now(timezone.utc).isoformat()
        with self._conectar() as conexao:
            conexao.execute(
                "INSERT INTO perfis_mapeamento "
                "(nome, assinatura, colunas_json, papeis_json, ordem_data, criado_em) "
                "VALUES (?, ?, ?, ?, ?, ?) "
                "ON CONFLICT(assinatura) DO UPDATE SET "
                "nome = excluded.nome, colunas_json = excluded.colunas_json, "
                "papeis_json = excluded.papeis_json, ordem_data = excluded.ordem_data, "
                "criado_em = excluded.criado_em",
                (nome, assinatura, json.dumps(colunas, ensure_ascii=False),
                 json.dumps(papeis, ensure_ascii=False), ordem_data, agora),
            )
            linha = conexao.execute(
                "SELECT * FROM perfis_mapeamento WHERE assinatura = ?", (assinatura,)
            ).fetchone()
        return self._perfil(linha)

    def listar_perfis_mapeamento(self) -> list[dict]:
        with self._conectar() as conexao:
            linhas = conexao.execute(
                f"SELECT * FROM perfis_mapeamento ORDER BY {self._ordem('criado_em')} DESC, id DESC"
            ).fetchall()
        return [self._perfil(linha) for linha in linhas]

    def perfil_por_assinatura(self, assinatura: str) -> dict | None:
        with self._conectar() as conexao:
            linha = conexao.execute(
                "SELECT * FROM perfis_mapeamento WHERE assinatura = ?", (assinatura,)
            ).fetchone()
        return self._perfil(linha) if linha else None

    def apagar_perfil_mapeamento(self, perfil_id: int) -> bool:
        with self._conectar() as conexao:
            cursor = conexao.execute("DELETE FROM perfis_mapeamento WHERE id = ?", (perfil_id,))
        return cursor.rowcount > 0

    def listar_curados(self) -> list[dict]:
        with self._conectar() as conexao:
            linhas = conexao.execute(
                f"SELECT * FROM lexico_curado ORDER BY {self._ordem('criado_em')} DESC, id DESC"
            ).fetchall()
        return [dict(linha) for linha in linhas]

    def revogar_curado(self, curado_id: int) -> bool:
        """`False` quando nao havia o que revogar -- e ai a versao NAO sobe.

        Subir a versao numa revogacao que nao aconteceu marcaria o banco inteiro
        como defasado sem nenhuma mudanca de lexico por tras.
        """
        with self._conectar() as conexao:
            cursor = conexao.execute(
                "DELETE FROM lexico_curado WHERE id = ?", (curado_id,)
            )
            if cursor.rowcount == 0:
                return False
            self._incrementar_versao(conexao)
        return True

    def carregar_curadoria(self) -> Curadoria:
        """Monta o objeto que os sinais consomem. Lido a cada requisicao."""
        palavras: dict[str, int] = {}
        emojis: dict[str, float] = {}
        with self._conectar() as conexao:
            for linha in conexao.execute("SELECT tipo, termo, peso FROM lexico_curado"):
                if linha["tipo"] == "palavra":
                    palavras[linha["termo"]] = int(linha["peso"])
                else:
                    emojis[linha["termo"]] = float(linha["peso"])
        return Curadoria(palavras=palavras, emojis=emojis, versao=self.lexico_versao())

    def contar_defasadas(self) -> tuple[int, int]:
        """(pontuadas com lexico anterior, total). Do banco INTEIRO.

        `lexico_versao IS NULL` e linha de banco anterior a este mecanismo, e
        vale ZERO: nao ha diferenca entre "pontuada antes da coluna existir" e
        "pontuada quando ninguem tinha curado nada" -- as duas usaram o lexico
        base puro.

        Por isso o `COALESCE`, e nao um `IS NULL` que conta como defasada
        sozinho: num banco que nunca teve curadoria, aquela regra marcava TODA
        conversa como pontuada com outra regua e a tela abria com um alarme
        falso de 64 de 64. O que distingue defasada de em dia e a versao VIGENTE
        ter andado -- se ela e 0, existe um lexico so, e nada pode estar atras.
        """
        vigente = self.lexico_versao()
        with self._conectar() as conexao:
            linha = conexao.execute(
                "SELECT COUNT(*) AS total, "
                "SUM(CASE WHEN COALESCE(lexico_versao, 0) <> ? "
                "THEN 1 ELSE 0 END) AS defasadas "
                "FROM conversas",
                (vigente,),
            ).fetchone()
        return int(linha["defasadas"] or 0), int(linha["total"] or 0)
